#pragma once
#include <glm/glm.hpp>
#include <random>
#include <cmath>
#include <chrono>
#include <eigen3/Eigen/Dense>
#include <texture.h>
#include <unordered_map>
#include <string>
#include "render_object.h"
